module.exports = class YoMomma {
    constructor() {
        this.jokes = [
            'Yo momma is so poor that she had to get a second mortgage on her cardboard box.',
            'Yo momma is so old that her memory is in black and white.',
            'Yo momma is so ugly that her pillow cries at night.',
            'Yo momma is so poor that when I saw her walking down the street with one shoe and said “Hey miss, lost a shoe?” she said “Nope, just found one!”',
            'Yo momma is so poor that she has to take the trash IN.',
            'Yo momma is so old that she walked into an antique store and they kept her.',
            'Yo momma is so ugly that she made an onion cry!',
            'Yo momma is so stupid that she uses Old Spice for cooking.',
            'Yo momma is so poor that she married young just to get the rice!',
            'Yo momma is so fat that she puts mayonnaise on aspirin.',
            'Yo momma is so poor that she washes paper plates.',
            'Yo momma is so poor that her face is on the front of a foodstamp.',
            'Yo momma is so fat that she has more Chins than a Chinese phone book!',
            'Yo momma is so ugly that when she sits in the sand on the beach, cats try to bury her.',
            'Yo momma is so poor that your TV got 2 channels: ON and OFF.',
            'Yo momma is so stupid that she thinks fruit punch is a gay boxer.',
            'Yo momma is so fat that that she cant tie her own shoes.',
            'Yo momma is so ugly that she makes blind children cry.',
            'Yo momma is so fat that she fell out of both sides of her bed.',
            'Yo momma is so ugly that she could scare the flies off a shit wagon.',
            'Yo momma is so old that when she farts, dust comes out.',
            'Yo momma is so stupid that she thinks Tiger Woods is a forest in India.',
            'Yo momma is so poor that your family ate cereal with a fork to save milk.',
            'Yo momma is so ugly that… well… look at you!',
            'Yo momma is so fat that she went to the movie theatre and sat next to everyone.',
            'Yo momma is so stupid that she thought Dunkin’ Donuts was a basketball team!',
            'Yo momma is so poor that burglars break in and leave money.',
            'Yo momma is so old that that when she was in school there was, no history class.',
            'Yo momma is so stupid that when she went for a blood test, she asked for time to study.',
            'Yo momma is so ugly that she scared the crap out of the toilet.',
            'Yo momma is so fat that when she sits around the house, she SITS AROUND THE HOUSE!',
            'Yo momma is so poor that she can’t afford to pay attention!',
            'Yo momma’s so dumb that when she saw the “Under 17 not admitted” sign at a movie theatre, she went home and got 16 friends.',
            'Yo momma is so fat that when she steps on a scale, it reads “one at a time, please”.',
            'Yo momma is so poor that the bank repossesed her cardboard box.',
            'Yo momma is so ugly that she could be the poster child for birth control.',
            'Yo momma so fat she goes to KFC and licks other people’s fingers.',
            'Yo momma so dumb when you stand next to her you hear the ocean!',
            'Yo momma so stupid, when I told her that she lost her mind, she went looking for it.',
            'Yo momma so fat Burger King hired her because she eats cows and shits hamburgers.',
            'Yo momma so fat she left the house in high heels and when she came back she had on flip flops.',
            'Yo momma so ugly, even hello kitty said goodbye.',
            'Yo momma so fat she ate a whole Pizza… Hut.',
            'Yo momma is so dumb she got awarded the Nobel prize for stupidity.',
            'Yo momma so ugly she threw a boomerang and it refused to come back.',
            'Yo momma so dumb she sold her car for gasoline money!',
            'Yo mommas so stupid she was yelling into the mailbox. We ask her what’s she doing and she said, she was sending a voice-mail.',
            'Yo momma so fat that she don’t need the internet she’s already world wide.',
            'Yo momma is so dumb not even Google could translate her.',
            'Yo momma so butch, her dick is bigger than mine.',
            'Yo momma so dirty she has to creep up on bathwater.',
            'Yo momma so fat she just had a baby and said it was delicious.',
            'Yo momma so greasy and fat she uses bacon as a band aid.',
            'Yo momma is so stupid when your dad sad it was chilly outside, she ran out the door with a spoon!',
            'Yo momma so fat all she wanted for Christmas is to see her feet.',
            'Yo momma so stupid she stuck a battery up her ass and said, “I GOT THE POWER!”',
            'Yo momma so dumb she thought a tsunami was a kind of Japanese sushi',
            'Yo Momma’s so fat when I told her to touch her toes she said, “What are those”?',
            'Yo momma so fat that she gave Dracula diabetes.',
            'Yo momma is so hairy, when she went to the movie theater to see Star Wars, everybody screamed and said, “IT’S CHEWBACCA!”',
            'Yo momma so fat and dumb, she tears apart computers looking for cookies.',
            'Yo momma is so fat, I took a picture of her last Christmas and it’s still printing.',
            'Yo momma so fat that when she took a selfie, Instagram crashed.',
            'Yo momma is so fat when she sat on WalMart, she lowered the prices.',
            'Yo mamma so ugly even Bob the Builder said, “We can’t fix it.”',
            'Yo momma is so fat when she got on the scale it said, “I need your weight not your phone number.”',
            'Yo momma so fat she went to a restaurant and got the group discount.',
            'Yo momma’s so fat, that when she fell, no one was laughing but the ground was cracking up.',
            'Yo momma is so stupid, when they said, “Order in the court,” she asked for fries and a shake.',
            'Your momma is so ugly she made One Direction go the other way.',
            'Yo momma so nasty she looks like an ogre and smells like puss in boots.',
            'Yo momma is so stupid when an intruder broke into her house, she ran downstairs, dialed 9-1-1 on the microwave, and couldn’t find the “CALL” button.',
            'Yo momma so fat sets off car alarms when she runs.',
            'Yo momma’s so stupid, she put two quarters in her ears and thought she was listening to 50 Cent.',
            'Yo momma so fat her blood type is Nutella.',
            'Yo momma is so fat that Dora can’t even explore her!',
            'Yo momma is so fat that when she gets in an elevator, it has to go down.',
            'Yo momma is so stupid she climbed over a glass wall to see what was on the other side.',
            'Yo momma so fat, every time she walks she does the Harlem shake.',
            'Yo momma’s so dumb, when y’all were driving to Disneyland, she saw a sign that said “Disneyland left,” so she went home.',
            'Yo momma so ugly when Santa came down the chimney he said ho! ho! hoooollly shit!',
            'Yo momma is so fat, when she sat on an iPod, she made the iPad!',
            'Yo momma is so fat that when she was diagnosed with a flesh-eating disease, the doctor gave her ten years to live.',
            'Yo mamma is so ugly when she took a bath the water jumped out.',
            'Yo momma so dumb she got locked in a grocery store and starved!',
            'Yo momma is so fat when she went to KFC the cashier asked, “What size bucket?” and yo momma said, “The one on the roof.”',
            'Yo momma so dumb when yo father said let’s hit the Road she actually hit the road.',
            'Yo momma is so fat that when she saw a yellow school bus go by full of white kids she ran after it yelling, “TWINKIE!”',
            'Yo momma is so fat she threw on a sheet for Halloween and went as Antarctica.',
            'Yo momma is so stupid she took a ruler to bed to see how long she slept.',
            'Yo momma so fat, they used Google Earth for her school photo.',
            'Yo momma so ugly when she went into a haunted house she came out with a job application.',
            'Yo momma so fat she jumped in the air and got stuck.',
            'Yo momma is so poor I saw her kicking a trash can so I asked, “What are you doing?” and she said, “I’m moving.”',
            'Yo momma is so poor, she chases the garbage truck with a grocery list.',
        ]
    }
}